// src/fragen.js

/*
    add new questions here. please refrain from pushing when you don't know what you're doing.

    If fragen.js has been changed, do the following:
        - git status (check if fragen.js has been changed)
        - git add src/fragen.js
        - git commit -m "added questions!"
        - git push origin main

        - npm run deploy (to update the gh-pages branch)
*/

const fragen = [
    "Beschreibe die Person rechts von dir als einen fiktiven Charakter.",
    "Was ist dein peinlichster Kindheitscrush?",
    "Was ist dein größter Hottake?",
    "Welche Person im Raum hat den besten Style?",
    "Mit welcher Person habt ihr den letzten Monat die meiste Zeit verbracht?",
    "Wer ist dein aktueller Crush?",
    "Welche Person im Raum hat die meiste Zeit in ihrem Leben vor dem PC verbracht?",
    "Wer verbringt die meiste Zeit am Tag mit Shortsvideos?",
    "Was ist der letzte Traum, an den du dich erinnerst?",
    "Was ist die härteste Droge, die du jemals genommen hast?",
    "Welches Tier wärt ihr am liebsten?",
    "Was findest du an dir am attraktivsten?",
    "Als welche fiktive Figur würdet ihr euch selber beschreiben?",
    "Welche Eigenschaft schätzt du am meisten bei anderen?",
    "Welche Farbe findet ihr am hässlichsten?",
    "Welche Haarfarbe findet ihr am attraktivsten?",
    "Was würdest du machen, wenn du nur noch eine Stunde zu leben hättest?",
    "Was ist dein größter Kink?",
    "Was ist das exotischste, was du je gegessen hast?",
    "Warst du jemals schon in eine Schlägerei verwickelt?",
    "Was ist die unangenehmste Situation, in der du von deinen Eltern erwischt wurdest?",
    "Was ist die längste Zeit, in der du dir nicht die Zähne geputzt hast?",
    "Welche Person in der Runde wird am ehesten als nächstes heiraten?",
    "Was ist das komischste, ohne Kontext, dass du je gegoogled hast?",
    "Welche deiner Eigenschaften wünschst du dir, dass sie stärker ausgeprägt wäre?",
    "Welche deiner Eigenschaften wünschst du dir, dass sie schwächer ausgeprägt wäre?",
    "Was war deine dümmste Verletzung?",
    "Wann und warum hast du das letzte Mal geweint?",
    "Mit welchem Overwatch Charakter würdest du am ehesten ins Bett steigen?",
    "Wer ist die schönste Person, die du kennst?",
    "Wann hast du zuletzt geklaut?",
    "Mit welcher Person in der Runde würdet ihr am ehesten den Rest eures Lebens verbringen?",
    "Wann zuletzt Hand angelegt?",
    "Welches Körperteil findest du am attraktivsten?",
    "Existiert irgendwo ein Nacktbild von dir?",
    "Würdest du im Bett lieber die Top- oder Botlane bespielen?",
    "Lieblings Pornkategorie?",
    "Mach deinem linken Sitznachbar ein Kompliment.",
    "Trink 5 Schlücke.",
    "Trink 8 Schlücke.",
    "Trink 3 Schlücke.",
    "Zeig der Gruppe dein peinlichstes Foto/Video von dir.",
    "Was ist deine Lieblingsbeleidigung?",
    "Lieber die ersten 90% oder die letzten 10% eines Blowjobs tätigen?",
    "Spielt eine Runde 'Wer bin Ich?'.",
    "Spielt eine Runde 'Bulgarisches', der Verlierer trinkt 6 Schlücke.",
    "Spielt eine Runde 'Tabu'.",
    "Spielt eine Runde 'Pantomime'.",
    "Spielt eine Runde 'Montagsmaler', falls möglich.",
    "Lege einen Catwalk hin.",
    "Wer in der Runde hat den geilsten Arsch?",
    "Was glaubt ihr ist der versauteste Teilnehmer in der Runde?",
    "Wer würde eher einem Kind den Lolli wegnehmen?",
    "Wer würde eher einen Fremden küssen?",
    "Wer würde eher No Nut November durchziehen?",
    "Wer würde eher im Internet viral gehen?",
    "Welche Person der Gruppe wird den dümmsten Tod sterben?",
    "Wer würde eher für Sex bezahlen?",
    "Wer würde eher für Sex Geld annehmen?",
    "Wer würde am ehesten in den Knast kommen?",
    "Wer würde als erstes in ner Zombieapokalypse sterben?",
    "Wer würde eine Zombieapokalypse am längsten überleben?",
    "Wer würde eher eine AI daten?",
    "Hast du schonmal externe Mittel zum masturbieren benutzt.",
    "Zeig 3 Tanzschritte.",
    "Hast du schonmal feucht geträumt?",
    "Habt ihr schonmal neben das Klo gepisst?",
    "Hast du schonmal in der Öffentlichkeit gekotzt?",
    "Von wem wurdet ihr zuletzt gekorbt?",
    "Hast du schonmal illegal Geld verdient?",
    "Ich hab noch nie so einen schlechten Witz erzählt, dass ich ihn erklären musste.",
    "Ich hab noch nie etwas durch die Nase genommen.",
    "Hast du schonmal unter freiem Himmel geschlafen?",
    "Ich hab noch nie in Videospielen gecheated.",
    "Welcher League of Legends Champion hat die rassistischsten Mains?",
    "Lieber falsche Keystone Mastery auswählen oder falsches Startitem kaufen?",
    "Was ist das unattraktivste Hobby?",
    "Kim Possible oder Shego?",
    "Lieber in die Wand flashen oder Canonminion verpassen?",
    "Was ist das größte Geheimnis, das du vor deinen Eltern verheimlicht hast?",
    "Was ist dein Celebrity Crush?",
    "Wem schickst du die meisten Shortsvideos?",
    "Lieber Liebes- oder Horrorfilme?",
    "Was ist die bodenloseste Ausrede, die du je benutzt hast, um ein Treffen abzusagen?",
    "Was ist deine größte Guilty Pleasure Serie?",
    "Was ist deine Lieblings Kindheitsserie?",
    "Welche fiktive Figur würdest du daten?",
    "Wo war dein Lieblingsurlaub?",
    "Was ist euer aktueller Lieblingssong?",
    "Lieber nie wieder Filme oder nie wieder Serien gucken?",
    "Welchen Spieler kennst du am besten?",
    "Welcher Spieler kennt dich am besten?",
    "Welche Straftat würdest du begehen, wenn sie danach nie wieder begangen werden könnte?",
    "Alle Raucher verteilen so viele Schlücke wie sie Kippen in der Schachtel haben.",
    "Welcher Film oder Serie hat dich zuletzt zum Weinen gebracht?",
    "Mit welcher berühmten Person, egal ob tot oder lebendig, würdest du dich gerne einmal unterhalten?",
    "Hattet ihr jemals einen Crush auf ein Familienmitglied eines guten Freundes?",
    "Wenn du dir heute ein Tattoo stechen lassen müsstest, was wäre das Motiv?",
    "Welches Videospiel ist komplett overrated?",
    "Welcher Film oder Serie ist maßlos overrated?",
    "Für was hast du am meisten Stress in der Schule bekommen?",
    "Was ist deine größte Phobie?",
    "Welcher Song lässt dich am härtesten allein daheim tanzen?",
    "Was ist deine peinlichste Betrunken-Heimweg-Geschichte?",
    "Was ist euer Lieblingsemoji und warum?",
    "Wen im Raum würdest du in einem Armdrücken besiegen?",
    "Beschreibe die attraktivsten Körperteile deiner Mitspieler.",
    "Zeige deine Handy Screentime der letzten Woche.",
    "Spielt eine Runde 'Zwei Lügen, eine Wahrheit'.",
    "Spielt eine Runde 'Tabu'.",
    "Spielt eine Runde 'Pantomime'.",
    "Verteile so viele Schlücke wie du Liegestütze schaffst, maximal 20.",
    "Welches Tier beschreibt deinen linken Sitznachbar am besten.",
    "Was wissen deine Eltern noch heute nicht über dich?",
    "Welche Eigenschaft bewunderst du an deinem rechten Nachbarn am meisten?",
    "Welchen Film oder Serie wünschst du dir, hätten mehr Personen geguckt?",
    "Lieber Star Wars oder Herr der Ringe?",
    "Welchem Hogwartshaus gehörst du an?",
    "In welches Hogwartshaus würdet ihr euren linken Sitznachbar einteilen.",
    "Zählt nacheinander 'Pokémon' auf bis einer keine mehr weiß.",
    "Zählt nacheinander Star-Wars-Charaktere bis einer nicht mehr kann.",
    "Zählt nacheinander Harry-Potter-Charaktere bis einer nicht mehr kann.",
    "Zählt nacheinander League of Legends Champions auf bis einer nicht mehr kann.",
    "Zählt nacheinander Filmgenres auf bis einer nicht mehr kann.",
    "Zählt nacheinander Musikgenres auf bis einer nicht mehr kann.",
    "Zählt nacheinander Vögel auf bis einer nicht mehr kann.",
    "Zählt nacheinander Videospiele auf bis einer nicht mehr kann.",
    "Trink 3 Schlücke.",
    "Trink 4 Schlücke.",
    "Trink 5 Schlücke.",
    "Trink 2 Schlücke.",
    "Gib einem Gruppenmitglied deiner Wahl einen Kuss auf die Wange.",
    "Hau eine Lebensweisheit raus.",
    "Welche Berühmtheit ist dir am unsympathischsten?",
    "Lieber Fishermans Friend oder Kaugummis?",
    "Was ist die beste Farbe für Nagellack?",
    "Siren oder Doe Eyes?",
    "Zählt nacheinander Filme mit einer Fortsetzung auf bis einer nicht mehr kann.",
    "Zählt nacheinander Alkoholarten auf bis einer nicht mehr kann.",
    "Zählt nacheinander Biermarken auf bis einer nicht mehr kann.",
    "Lieber mit Bart oder ohne Bart bei Männern.",
    "Zuerst das Müsli oder die Milch?",
    "Was schätzt ihr an eurem besten Freund am meisten?",
    "Piraten oder Ritter?",
    "Cowboys oder Astronauten?",
    "Erzähl uns einen Zauberspruch aus Bibi Blocksberg, falls du keinen weißt, trink 3 Schlücke.",
    "Lieber nicht mehr sprechen oder hören können.",
    "Zählt nacheinander Herr der Ringe Charaktere auf bis einer nicht mehr kann.",
    "Zählt nacheinander Rapper auf bis einer nicht mehr kann.",
    "Zählt nacheinander K-Pop Artists auf bis einer nicht mehr kann.",
    "Wenn ihr die Welt nur noch in einer Farbe wahrnehmen könntet, welche wäre es?",
    "Die Person die zuletzt jemanden angerufen hat darf 3 Schlücke verteilen.",
    "Die Person die zuletzt gekotzt hat muss 2 Schlücke trinken.",
    "Alle Personen die schwarze Socken anhaben trinken einen Schluck.",
    "Die Person die sich zuletzt ein Spiel gekauft, das nicht gespielt wurde, trinkt 5 Schlücke.",
    "Zählt nacheinander F1-Fahrer auf bis einer nicht mehr kann.",
    "Wer war eurer Meinung nach der beste Minecraft Hero Teilnehmer?",
    "Welcher League of Legends Charakter würde die meisten Matches auf Tinder bekommen?",
    "Eistee Pfirsich oder Zitrone?",
    "Wer aus diesem Raum dürfte nicht dein Kind daten.",
    "Wann hast du zuletzt jemand neues kennengelernt?",
    "Zeig deine letzte WhatsApp Nachricht.",
    "Nennt ein komisches Kompliment, das ihr schonmal bekommen habt.",
    "Schreib einem WhatsApp Kontakt deiner Wahl, dass du die Freundschaft mit ihm sehr wert schätzt.",
    "Vampire oder Werwölfe?",
    "Die Person die zuletzt trinken musste, trinkt nochmal 2 Schlücke.",
    "Trinke so viele Schlücke wie du Handyapps im Hintergrund offen hast.",
    "Was wolltest du schon immer einmal über die Person links von dir wissen?",
    "Verteile so viele Schlücke wie du Zweit- und Nachnamen der Gruppe aufzählen kannst.",
    "Verteile so viele Schlücke wie du Geburtstage aus der Gruppe kennst.",
    "Wer macht am meisten Sport in der Runde?",
    "Was ist euer Lieblingsschauspieler?",
    "Wer aus der Gruppe hat die meisten Leute geküsst?",
    "Was ist dein Type?",
    "Welche Fantasy Rasse würdest du gerne sein?",
    "Sollte dein Partner größer oder kleiner als du sein?",
    "Was wäre die größte Red Flag bei einem Date?",
    "Schneegolem oder Eisengolem?",
    "Lieber League of Legends Sohn oder Valorant Tochter?",
    "Beschreibe eine Charakteristik deines Traumpartners.",
    "Wer aus der Gruppe isst die meisten Tiefkühlpizzen?",
    "Nintendo oder Playstation Konsolen?",
    "Wer aus der Gruppe hat eurer Meinung nach den schlechtesten Musikgeschmack?",
    "Wer aus der Gruppe hat eurer Meinung nach den besten Musikgeschmack?",
    "Zählt nacheinander Kinderserien auf bis einer nicht mehr kann.",
    "Welche Kinderserie hatte das beste Intro?",
    "Welche Person steckt am tiefsten im Brainrot drin?",
    "Welche Person der Gruppe hat den verwirrtesten Wortschatz?",
    "Würde Batman oder Superman einen Kampf gewinnen?",
    "Wie viele Babys könntest du im Kampf nehmen?",
    "Welche Person der Gruppe hat den besten Seriengeschmack?",
    "Wer würde eher ein Date fürs Zocken canceln?",
    "Wer ist der spontanste in der Runde?",
    "Wer in der Runde verspricht sich am öftesten?",
    "Wer würde eher heute Nacht nicht alleine im Bett schlafen?",
    "Wer würde eher heute noch in Club gehen?",
    "Wer aus der Gruppe hat die letzte Woche am meisten Alkohol zu sich genommen?",
    "Spinnen oder Käfer schlimmer?",
    "Wer sagt am öftesten Treffen ab?",
    "Wer würde eher heute noch im Krankenhaus landen?",
    "Ich hab noch nie über einen Freund/Freundin fantasiert.",
    "Ich hab noch nie einen Crush auf einen sehr guten Freund gehabt.",
    "Ich hab noch nie ein Tinderdate gehabt.",
    "Jeder der auf einer Datingapp angemeldet ist, muss 4 Schlücke trinken.",
    "Der mit dem höchsten Clash of Clans Rathaus darf 5 Schlücke verteilen.",
    "Trink so viele Schlücke wie du mobile Games installiert hast.",
    "Sammelst du etwas?",
    "Ich hab noch nie die Zahnbürste jemand anderes genutzt.",
    "Ich hab noch nie eine Woche am Stück bei jemand anderes übernachtet.",
    "Was ist eure Lieblingspflanze?",
    "Ich hab noch nie einen Booty Call erhalten.",
    "Welche Eigenschaft schätzt ihr an eurem linken Nachbarn?",
    "Welche Charakteristik kannst du gar nicht leiden?",
    "Ich hab noch nie mit jemand im Club rumgemacht.",
    "Ich saß noch nie in einem Streifenwagen.",
    "Was ist das höchste Bußgeld, das du je zahlen musstest und für was?",
    "Wann hast du zuletzt etwas Illegales gemacht?",
    "Ich hab noch nie mir die Fingernägel lackiert.",
    "Hast du einen Crush auf einen imaginären Charakter, wenn ja, welchen?",
    "Welcher Musiker ist komplett overrated?",
    "Welcher Musiker ist deiner Meinung nach völlig underrated?",
    "Nenne eine Serie, die nur du gesehen hast, wenn sie ein anderer aus der Gruppe kennt, trinke 2 Schlücke.",
    "Nenne einen Musiker, den nur du hörst, wenn ihn ein anderer aus der Gruppe kennt, trinke 2 Schlücke.",
    "Ich hab noch nie mein Arsch rasiert.",
    "Ich hab noch nie zu Hentai masturbiert.",
    "Yu Gi Oh oder Pokémon Karten?",
    "Was sind deine Top 3 Influencer die du feierst?",
    "Daniel darf 5 Schlücke verteilen.",
    "Jeder, der sich mit Kaugummizigaretten schon mal etwas zu cool gefühlt hat, trinkt einen Schluck.",
    "Nennt reihum Spiele, die man während einer Autofahrt spielen kann.",
    "Jeder, der Lakritze mag, trinkt 5 Schlücke.",
    /* new questions */
    "Mit wem aus der Gruppe hast du zuletzt geschrieben, ihr beiden trinkt einen Schluck.",
    "Ich hab noch nie gedacht, dass ich zu viel masturbiere.",
    "Welchen Generation 1 Starter aus Pokémon wählst du? (Bisasam, Glumanda, Schiggy)",
    "Wer aus der Runde ist der schlechtechste Gamer?",
    "Wer aus der Runde ist der beste Gamer?",
    "Zählt nacheinander Zigarettenmarken auf, bis einer nicht mehr kann.",
    "Wenn du in einer fiktiven Welt leben müsstest, welche würdest du wählen?",
    "Welchen Duft kannst du gar nicht ausstehen?",
    "Welche Chipssorte ist die beste?",
    "Wann hast du zuletzt ein Buch aus eigenem Interesse gelesen?",
    "Wenn du weniger als 50 Stunden die letzte Woche geschlafen hast, verteile 3 Schlücke.",
    "Was halten wir von Percings bei anderen?",
    "Was ist eine Green Flag für dich auf einem Date?",
    "Welches Meme der letzten 5 Jahre findest du am nervigsten?",
    "Welchen Trend der letzten 10 Jahre findest du am stressigsten?",
    "Welcher Song schwirrt dir aktuell die ganze Zeit im Kopf herum?",
    "Wie viel Geld hast du schon in deinem Leben für Lego ausgegeben, wenn es über 300€ sind trinke 4 Schlücke.",
    "Wenn du einen Straßenteppich als Kind hattest, verteile 3 Schlücke.",
    "Welche Weisheit aus deiner Kindheit ist dir bis heute im Kopf geblieben?",
    "Stell uns deinen größten 'Hear me out'-Crush vor.",
    "Trinke so viele Schlücke, wie du Steamspiele in deiner Bibliothek hast, die du weniger als 30 Minuten gespielt hast. (maximal 10)",
    "Welche Serie oder Film hat dich zuletzt zum ernsthaften Nachdenken gebracht?",
    "Trink so viele Schlücke wie du Straßenschuhe besitzt.",
    "Verteile 2 Schlücke wenn du heute geduscht hast, trinke sie wenn nicht.",
    "Verteile so viel Schlücke wie du deutsche Nachbarländer aufzählen kannst.",
    "Verteile so viel Schlücke wie du Planeten aus unserem Sonnensystem, in der richtigen Reihenfolge aufzählen kannst, von der Sonne aus startend.",
    "Verteile 4 Schlücke, wenn du mehr als 7 afrikanische Länder aufzählen kannst.",
    "Zählt nacheinander Bundesligameister auf, bis einer nicht mehr kann.",
    "Wann hast du dich zuletzt intim rasiert?",
    "Verteile so viel Schlücke wie du Schlüssel dabei hast.",
    "Trinke 2 Schlücke wenn du noch nie Just Dance gespielt hast.",
    "Ich hab noch nie Tampons gekauft.",
    "Kaffee oder Tee?",
    "Warst du schon einmal wahrhaftig verliebt?",
    "Trinke 2 Schlücke wenn dir schonmal eine Pflanze gestorben ist.",
    "Welchen kürzlichen Kauf bereust du am meisten?",
    "Verteile so viel Schlücke wie du Beyblades besessen hast.",
    "Was ist dein Lieblings Lego Theme?",
    "Verteile 2 Schlücke wenn du früher einen Cityroller besessen hast.",
    "Du und die person aus der Gruppe mit der du am längsten nicht mehr geschrieben hast trinken beide einen Schluck."
];


export default fragen;
